language: node_js
node_js: stable

before_install: npm install -g yarn

deploy:
  provider: script
  script:
    - cd app && yarn build
    - cd app && yarn deploy
  skip_cleanup: true
  on:
    branch: master