language: node_js
node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules

build:
  only:
    - master

before_install: npm install -g yarn

before_script: yarn lint
script: yarn build -p

deploy:
  provider: script
  skip_cleanup: true
  script: yarn deploy
  on:
    branch: master
